version: "2"
run:
  tests: false
linters:
  enable:
    - bodyclose
    - errcheck
    - gosec
    - misspell
    - staticcheck
  settings:
    gosec:
      excludes:
        - G301  # directory permissions
        - G304  # file inclusion via variable (false positive for cache)
        - G306  # file permissions
    staticcheck:
      checks:
        - "all"
        - "-QF*"   # disable quick fix suggestions
        - "-S1009" # nil check before len is fine for readability
        - "-ST*"   # disable style rules (package comments, etc.)
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
