version: 2
project_name: kevs-tui

builds:
  - main: .
    binary: kevs-tui
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - id: default
    formats: ["tar.gz"]
    name_template: "{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}"
    format_overrides:
      - goos: windows
        formats: ["zip"]

checksum:
  name_template: 'checksums.txt'

sboms:
  - artifacts: archive

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - Merge pull request
      - Merge branch

release:
  github:
    owner: ethanolivertroy
    name: kevs-tui

brews:
  - repository:
      owner: ethanolivertroy
      name: homebrew-sectools
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
    directory: Formula
    homepage: "https://github.com/ethanolivertroy/kevs-tui"
    description: "Terminal UI for browsing CISA Known Exploited Vulnerabilities (KEV)"
    license: "MIT"
    install: |
      bin.install "kevs-tui"
    test: |
      assert_match "KEV", shell_output("#{bin}/kevs-tui --help 2>&1", 1)

scoops:
  - repository:
      owner: ethanolivertroy
      name: scoop-sectools
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
    directory: bucket
    homepage: "https://github.com/ethanolivertroy/kevs-tui"
    description: "Terminal UI for browsing CISA Known Exploited Vulnerabilities (KEV)"
    license: "MIT"
